name: Test
on: [push]
jobs:
  test:
    name: Test PHP ${{ matrix.php-version }}, Laravel ${{ matrix.laravel-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.3', '7.4']
        laravel-version: ['5.7.*', '5.8.*', '^6.0', '^7.0', '^8.0']
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - uses: actions/checkout@v2
      - run: composer self-update
      - run: 'composer require laravel/framework:${{ matrix.laravel-version }}'
      - run: composer install --no-interaction --prefer-source
      - run: composer test
      - run: composer analyze
