name: Test
on: [push]
jobs:
  test:
    name: Test PHP ${{ matrix.php-version }}, Laravel ${{ matrix.laravel-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4']
        laravel-version: ['^6.0']
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
